### ISSUE TITLE
Live (or cached) docker hub pull stats on home page

### ISSUE THREAD

**Issue by ogarrett** [deepfence/DocumentationWebsite#9]
Notes:

* `curl -s https://hub.docker.com/v2/repositories/deepfenceio/deepfence_agent_ce | jq '.pull_count'`

**Comment by rs280** [comment]
Hello Owen, I am not familiar with makefiles, so I need some of your help with this.

I am trying to download a file for docker pulls using this command
'curl https://hub.docker.com/v2/repositories/deepfenceio/deepfence_agent_ce -o docker.json'

I am not sure how to add this to the Makefile.
Please advise.

Thanks,
Rishabh

**Comment by rs280** [comment]
Turns out this website is not CORS enabled, so I cannot request it

**Comment by ogarrett** [comment]
Fixed with https://github.com/deepfence/DocumentationWebsite/commit/c78ac2d58891172f6239376e53368c0a16fe1662 and the use of an NGINX proxy to cache the API responses and add a 'access-control-allow-origin: *' response header
